service: ladder-api

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  createUser:
    handler: endpoints/createUser.main
    events:
      - http:
          path: user/createnew
          method: post
          cors: true
          authorizer: aws_iam
  getUser:
    handler: endpoints/getUser.main
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
          authorizer: aws_iam
  updateUser:
    handler: endpoints/updateUser.main
    events:
      - http:
          path: user/{id}
          method: put
          cors: true
          authorizer: aws_iam
  createPost:
    handler: endpoints/createPost.main
    events:
      - http:
          path: post/createnew
          method: post
          cors: true
          authorizer: aws_iam
  getLocalPosts:
    handler: endpoints/getLocalPosts.main
    events:
      - http:
          path: posts
          method: get
          cors: true
          authorizer: aws_iam
  getPosts:
    handler: endpoints/getPosts.main
    events:
      - http:
          path: posts/{userId}/{postId}
          method: get
          cors: true
          authorizer: aws_iam
      - http:
          path: posts/{userId}
          method: get
          cors: true
          authorizer: aws_iam